### ISSUE TITLE
Automate releases

### ISSUE THREAD

**Issue by garrytrinder** [garrytrinder/dev-proxy-toolkit#33]
Make it easy to push new versions to the marketplace

**Comment by garrytrinder** [comment]
This code will publish a new version of the extension when a new tag is added to the repo.

```yml
name: Publish VS Code Extension

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 'lts/*'

    - name: Install Dependencies
      run: npm ci

    - name: Install VSCE
      run: npm install -g vsce

    - name: Publish
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}
      run: vsce publish
```
